/// Flutter icons AppIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData ic_ic_back = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_ic_clock = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_ic_holidays = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_ic_meeting = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_ic_profil_selected = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ic_ic_project = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData ic_ic_trombi = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData ic_ic_wallet = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData ic_password = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData ic_user = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData shape = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData bt_bt_add = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData bt_validate = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData ic_add = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData ic_chevron_left = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData ic_ic_arrow = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData ic_ic_info = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData ic_ic_clock_1 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData ic_ic_holidays_1 = const IconData(0xe812, fontFamily: _kFontFam);
}
